### ISSUE TITLE
Device Nicknames - Ability to Edit

### ISSUE THREAD

**Issue by 2rc** [onnet/mod_kazoo#2]
It would be useful if I could change the nicknames for my devices. For example, I recently moved some of the extensions around on my SPA phone so the device that is nicknamed "SPA525G Line 2" is now on line 1. Ideally I would like to rename it accordingly.

**Comment by onnet** [comment]
@2rc thanks for a hint. Will take a look at it.

**Comment by onnet** [comment]
@2rc Done.
