### ISSUE TITLE
User Portal - Webphone Instructions for Use

### ISSUE THREAD

**Issue by 2rc** [onnet/mod_kazoo#3]
Does this feature enable the user to make calls directly from the portal? Currently the description just says "Please choose sip device to register with."

**Comment by onnet** [comment]
@2rc Yep, you need to choose the device to register with and will be able to use it as a webphone after registration. It is not very slick yet but you can place calls for sure :)

**Comment by 2rc** [comment]
Cool, in that case I we could change the words "Please choose sip device to register with" to something more descriptive, like the following:

Choose a device to register, then make calls from right here in your web browser.

**Comment by onnet** [comment]
@2rc Done. Thanks!
